services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smarthome
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./smart_home/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - smart_home_network

  temperature-api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: smart_home_temperature_api
    ports:
      - "8081:8081"
    entrypoint: ["python", "temperature_api.py"]
    networks:
      - smart_home_network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smart_home_network

volumes:
  postgres_data:

networks:
  smart_home_network:
    driver: bridge
    name: smart_home_network
