graph TB
    subgraph "ЭТАП 5"
        Gateway["API Gateway"]
        Kafka["Kafka"]

        User["User"]
        Device["Device"]
        Heating["Heating"]
        Lighting["Lighting
        порт 8083"]
        Access["Access
        порт 8084"]
        Surveillance["Surveillance
        порт 8085"]
        Scenarios["Scenarios
        порт 8087"]
    end

    Client --> Gateway
    Gateway --> User
    Gateway --> Device
    Gateway --> Heating
    Gateway --> Lighting
    Gateway --> Access
    Gateway --> Surveillance
    Gateway --> Scenarios

    subgraph "Event Bus"
        Kafka
    end

    User --> Kafka
    Device --> Kafka
    Heating --> Kafka
    Lighting --> Kafka
    Access --> Kafka
    Surveillance --> Kafka
    Scenarios --> Kafka